name             'dbag'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures dbag'
long_description 'Installs/Configures dbag'
version          '0.1.0'
